---
gametime-project:
  file:
    location: producerreactor_reaction_function_3.c
    analysis-function: _producerreactorreaction_function_3
    start-label: null
    end-label: null


  preprocess:
    include: null
    merge: null
    inline: yes
    unroll-loops: Yes

  analysis:
    maximum-error-scale-factor: 10
    determinant-threshold: 0.001
    max-infeasible-paths: 100
    ilp-solver: glpk
    gametime-flexpret-path: ../flexpret/
    gametime-path: ../../
    gametime-file-path: ../../../..
